server:
  port: ${PORT:8189}
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /statico/**

  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        id:
          new_generator_mappings: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}

#    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
