server:
  hostname: localhost
  port: ${PORT:8189}
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=jxmlparse_valcurs}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    flyway:
      baseline-on-migrate: true
#  jackson:
#    serialization:
#      indent_output: true

mail:
  server:
    host: smtp.gmail.com
    port: 25
    username: egor.barinov@gmail.com
    password: ${hidden.email.password}






