-- drop schema if exists jxmlparse_valcurs cascade;
-- create schema jxmlparse_valcurs;
set search_path to jxmlparse_valcurs;

create table jxmlparse_valcurs.course (
                                          date date not null,
                                          primary key (date)
);

create table jxmlparse_valcurs.currencies (
                                              pk int8 generated by default as identity,
                                              char_code varchar(255),
                                              id varchar(255),
                                              name varchar(255),
                                              nominal numeric(19, 2),
                                              num_code varchar(255),
                                              value numeric(19, 2),
                                              primary key (pk)
);

create table jxmlparse_valcurs.entry_query (
                                               users_audit_entries int8 not null,
                                               id int8 not null
);

create table jxmlparse_valcurs.rate_valute_mapping (
                                                       course_date date not null,
                                                       currencies_pk int8 not null
);

create table jxmlparse_valcurs.users (
                                         id int8 generated by default as identity,
                                         activate_code varchar(255),
                                         email varchar(255),
                                         enabled boolean,
                                         password varchar(255),
                                         role varchar(255),
                                         username varchar(255),
                                         primary key (id)
);

create table jxmlparse_valcurs.users_audit_entries (
                                                       id int8 generated by default as identity,
                                                       query_date timestamp,
                                                       query_string varchar(255),
                                                       primary key (id)
);

alter table if exists jxmlparse_valcurs.entry_query
    add constraint UK_elepocc755hk4c0l8pjhsd3pt unique (id);

alter table if exists jxmlparse_valcurs.rate_valute_mapping
    add constraint UK_4ny6vblempitjadlvg6s2b7lq unique (currencies_pk);

alter table if exists jxmlparse_valcurs.entry_query
    add constraint FK9agiiedw823abr5i6vu2c5lei
    foreign key (id)
    references jxmlparse_valcurs.users_audit_entries;

alter table if exists jxmlparse_valcurs.entry_query
    add constraint FK2yr2gbsx7ao67bfhdkpiljwwg
    foreign key (users_audit_entries)
    references jxmlparse_valcurs.users;

alter table if exists jxmlparse_valcurs.rate_valute_mapping
    add constraint FK3dg33sexvjiys673ua0i14kj6
    foreign key (currencies_pk)
    references jxmlparse_valcurs.currencies;

alter table if exists jxmlparse_valcurs.rate_valute_mapping
    add constraint FKi5jh5a873soqkrjuq7s7r21nc
    foreign key (course_date)
    references jxmlparse_valcurs.course;

insert into jxmlparse_valcurs.users (username, password, email, enabled, role)
values
('user', '$2y$12$EFgNamlZ08x/UXolq6ajreNjOMmDlwRqPWyr4iUUMKGJn/35GVoau', 'user@gmail.com', true, 'ADMIN');

insert into jxmlparse_valcurs.users (username, password, email, enabled, role)
values
('guest', '$2y$12$LBqO6QQGcAYMTXI8VaCus.Mu3KPW5pDEtBRwrAj79/4RjRtSNuoLC', 'guest@gmail.com', true, 'CLIENT');